modules:
  - name: global-settings
    id: global-settings
    type: config
    config_files:
      - settings.yml

  - name: cluster
    id: cluster
    type: stack
    config_files:
      - settings.yml
      - logging.yml

  - name: identity-provider
    id: identity-provider
    type: stack
    config_files:
      - settings.yml

  - name: directoryservice
    id: directoryservice
    type: stack
    config_files:
      - settings.yml

  - name: shared-storage
    id: shared-storage
    type: stack
    config_files:
      - settings.yml

  - name: cluster-manager
    id: cluster-manager
    type: app
    config_files:
      - settings.yml

  - name: virtual-desktop-controller
    id: vdc
    type: app
    config_files:
      - settings.yml

    {% if 'bastion-host' in enabled_modules %}
  - name: bastion-host
    id: bastion-host
    type: app
    config_files:
      - settings.yml
    {% endif %}
