public: {{ alb_public | lower }}
instance_type: t3.medium
base_os: {{base_os}}
instance_ami: {{instance_ami}}
volume_size: {{volume_size}}
hostname: "{{module_id}}.{{cluster_name}}.{{aws_region}}.local"

logging:
  logs_directory: /opt/idea/app/logs
  profile: production
  default_log_file_name: application.log

cloudwatch_logs:
  enabled: true

ec2:
  # enable detailed monitoring for bastion-host ec2 instance, disabled by default
  enable_detailed_monitoring: false
  # enable termination protection for bastion-host ec2 instance, disabled by default
  enable_termination_protection: false
  # instance metadata access method
  metadata_http_tokens: "required"  # supported values are "required" for IMDSv2 or "optional" for IMDSv1
